# This is the step will builds and push new container image to "google container registry(GCR)"
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fnote-taking-gke-dev', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fnote-taking-gke-dev']

# This step is to deploy container to GKE
steps:
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
       - run
       - --filename=gke.yaml
       - --image=gcr.io/$PROJECT_ID/fnote-taking-gke-dev
       - --location=ap-south1-b
       - --cluster=cluster-1
       - --namespace=dev
